### ISSUE TITLE
Timestamps in the form "99.999s" fail to parse

### ISSUE THREAD

**Issue by franontanaya** [pculture/babelsubs#21]
Relevant code in storage.py

https://github.com/pculture/babelsubs/blob/96d3b15433fe81f0c1bfe629c4db5a748bbb1740/babelsubs/storage.py#L153

SubtitleEdit's "Timed Text 1.0" export uses timestamps in the form 
`\<p begin="78.9s" id="p25" end="82.905s"\>`

Which fail to post with the response {"errors": {"draft": "Time expression #.###s can't be parsed"}, "success": false}

**Comment by bendk** [comment]
This should be fixed in our next deploy.
